"""所有要用生圖工具生的圖，集中在這裡：檔名、尺寸、提示詞、參考圖。
img/README.md 和生圖清單網頁都由 tools/make_art_pack.py 從這裡產生；tools/prep_images.py 也照這裡的規格處理。
改提示詞就改這個檔，再跑一次 make_art_pack.py。
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 每張都加的風格基底（跟現在的碼頭、草原、第一隻狗同一套）
STYLE = ("hand-painted watercolor and gouache illustration in the style of a 1990s Japanese animated film, "
         "soft edges, warm natural light, gentle pastel colors, children's picture book mood, "
         "no text, no letters, no numbers, no watermark")

# 輸出規格：處理工具照這個裁切縮放
SPECS = {
    'bg': {'ratio': 3 / 2, 'size': (1536, 1024), 'label': '1536×1024，橫的 3:2'},
    'card': {'ratio': 3 / 4, 'size': (600, 800), 'label': '600×800，直的 3:4'},
    'dog': {'ratio': 13 / 15, 'size': (520, 600), 'label': '520×600，透明背景'},
    'sheet': {'ratio': 1, 'size': (384, 384), 'label': '切成每張 384×384，透明背景'},
}

# ---- 第一優先：六位救援隊員（2026-09-29 第二版：水彩加彩色鉛筆的卡通貼紙風，六種不同的動物）----
# 網站是公開的，角色一定要原創：動物、帽子、制服、隊徽都不能跟任何現有卡通（特別是汪汪隊）一樣。
# 檔名沿用 dog-0 … dog-5（程式、存檔都用這個編號），裡面不一定是狗。
# 我們的隊徽：金色圓形徽章，上面一根白色骨頭加一顆星星。不用爪印，也不用盾牌形。
DOG_STYLE = ("cute cartoon baby animal character, hand-drawn watercolor and colored pencil illustration, soft pencil outlines, "
             "big friendly round eyes, gentle smile, children's picture book style, "
             "an ORIGINAL character design that does not resemble any existing cartoon, TV show or toy character, "
             "no paw print symbols, no shield shaped badges, no text, no letters, no numbers, no watermark")
BADGE = "a small round golden team badge with a white bone and a little star on it"
BLUE_BG = "Put the character on a plain solid bright blue background (pure #1E4BFF), no shadow, no gradient, no checkerboard pattern."
# dog-0 從零生；其他五位上傳新的 dog-0 當「畫風參考」重畫（不是改圖）：畫風、線條、大小一樣，動物和動作各自不同。
# 每位都是全身、置中、臉朝前看得清楚（首頁頭像、商店、結算都用同一張）。不拿釣竿：釣魚遊戲的釣竿由程式另外畫在碼頭上。
FRAMING = ("Full body, centered, the character fills about 80 percent of the picture height, "
           "facing mostly toward the viewer so the face is clearly visible.")
DOG_BASE = ("A Shiba Inu puppy with cream and orange fur, standing on its hind legs and giving a cheerful salute with its right paw. "
            "It wears a soft round blue police cap with " + BADGE + " on the front, and a blue vest with a thin white reflective stripe. "
            + FRAMING + " " + DOG_STYLE + ". " + BLUE_BG)
DOG_EDIT = ("Use the attached picture only as a style reference. Draw a NEW character in exactly the same drawing style, "
            "the same line quality and coloring, the same size and framing as the reference, but with its own pose: {change}. "
            "It has " + BADGE + " on its hat or vest. " + FRAMING + " "
            "It must be an original character, not like any existing cartoon. " + BLUE_BG)
DOGS = [
    ('dog-1', '消防象', '#C8553D', "a baby elephant with soft grey skin and big round ears, wearing a red firefighter helmet with a wide round brim and a red jacket with two yellow stripes, "
     "sitting and happily spraying a small arc of water from its raised trunk"),
    ('dog-2', '醫護兔', '#E39AA8', "a fluffy white baby bunny with long upright ears, wearing a pink nurse cap with a small white heart and a pink vest, "
     "standing and holding a small pink first-aid box with a heart on it in both paws (no red cross symbol)"),
    ('dog-3', '森林熊', '#6B9E6B', "a brown bear cub with round ears, wearing a green forest ranger hat with a leaf on it and a green vest, "
     "standing and looking through small binoculars held in both paws"),
    ('dog-4', '工程河狸', '#E0955B', "a baby beaver with brown fur, two big front teeth and a flat tail, wearing a round orange construction hard hat and an orange safety vest with reflective stripes, "
     "standing and proudly holding up a small wooden hammer in one paw"),
    ('dog-5', '廚師貓', '#E8C86A', "an orange tabby kitten with a striped tail, wearing a tall white chef hat and a yellow apron, "
     "standing and flipping a pancake in a small frying pan"),
]

# ---- 第二優先：首頁七張卡片 ----
CARD_TAIL = "vertical 3:4 portrait format, one clear centered subject with big simple shapes, " + STYLE
CARDS = [
    ('card-fishing', '釣魚', "a small wooden pier over calm teal water on a sunny day, a fishing line dangling into the water where one big round shiny soap bubble floats, fluffy clouds"),
    ('card-whack', '打地鼠', "a sunny vegetable garden with three round dark soil holes in soft grass, one round cream-colored ball peeking out of the middle hole, carrot leaves and small flowers around"),
    ('card-memory', '翻牌', "four playing cards lying on a checked picnic blanket in the grass, two face down with a paw print on the back, two face up with plain white faces, a few daisies"),
    ('card-match', '連連看', "a small cork board with two picture cards pinned on it, one of a cat and one of an apple, joined by a red yarn string, soft light"),
    ('card-fill', '填空', "a wooden jigsaw puzzle board with one piece missing and that puzzle piece floating just above the gap with a soft glow"),
    ('card-tone', '聲調填空', "a row of four little wooden music bells on a windowsill, each a different height like steps going up and down, a small songbird perched on the tallest one, soft morning light"),
    ('card-write', '寫給狗狗看', "a small slate chalkboard on a wooden easel next to a fat yellow pencil and crayons, on a sunny windowsill"),
    ('card-learn', '學寫字', "a small wooden writing board on an easel with one big brush stroke glowing softly on it, a fat pencil with a tiny arrow ribbon, a few paper stars around, on a sunny windowsill"),
    ('card-speak', '唸給狗狗聽', "an old-fashioned round microphone on a little stand in a flower meadow, soft sound ripples and small musical notes floating out of it"),
]

# ---- 第三優先：遊戲背景。手機直拿時只看得到中間一段，中間又要夠安靜，遊戲的東西才看得清楚 ----
BG_TAIL = ("wide 3:2 landscape format, the middle of the picture is open and calm with little detail because game pieces are placed on top, "
           "the nicer details stay near the left and right edges, " + STYLE)
BGS = [
    ('bg-garden', '打地鼠', "a wide sunny vegetable garden meadow with a low wooden fence, sunflowers and bean poles at the far left and right, soft grass and brown earth across the lower half, distant hills and big clouds"),
    ('bg-room', '翻牌、連連看、填空、寫字、唸', "the cozy inside of a wooden treehouse classroom, sunlight through a round window with green leaves, bookshelves and potted plants at the left and right, a soft woven rug on the floor, warm and low contrast"),
    ('bg-shop', '狗狗商店', "a small cozy pet accessory shop, wooden shelves with colorful hats, scarves, bows and toys along the left and right walls, little bunting flags, warm afternoon light"),
]

# ---- 第四優先：74 個詞的圖。一次九張（3×3），處理工具會自動切開 ----
GLOSS = {
    '爸爸': 'dad',
    '媽媽': 'mom',
    '哥哥': 'older brother',
    '姐姐': 'older sister',
    '弟弟': 'little brother',
    '妹妹': 'little sister',
    '爺爺': 'grandpa',
    '奶奶': 'grandma',
    '阿姨': 'auntie',
    '叔叔': 'uncle',
    '小狗': 'puppy',
    '小貓': 'kitten',
    '小鳥': 'little bird',
    '小魚': 'little fish',
    '老虎': 'tiger',
    '獅子': 'lion',
    '大象': 'elephant',
    '兔子': 'rabbit',
    '猴子': 'monkey',
    '熊貓': 'panda',
    '青蛙': 'frog',
    '蝴蝶': 'butterfly',
    '蘋果': 'apple',
    '香蕉': 'banana',
    '西瓜': 'watermelon',
    '麵包': 'bread loaf',
    '牛奶': 'glass of milk',
    '雞蛋': 'egg',
    '餅乾': 'cookie',
    '糖果': 'wrapped candy',
    '蛋糕': 'slice of cake',
    '米飯': 'bowl of rice',
    '水果': 'bowl of mixed fruit',
    '草莓': 'strawberry',
    '眼睛': 'a pair of eyes',
    '鼻子': 'nose',
    '耳朵': 'ear',
    '嘴巴': 'smiling mouth',
    '頭髮': 'hair on a head, back view',
    '牙齒': 'tooth',
    '手指': 'hand pointing one finger',
    '腳丫': 'bare foot',
    '紅色': 'red paint blob',
    '黃色': 'yellow paint blob',
    '藍色': 'blue paint blob',
    '綠色': 'green paint blob',
    '白色': 'white paint blob on light grey',
    '黑色': 'black paint blob',
    '粉紅': 'pink paint blob',
    '紫色': 'purple paint blob',
    '吃飯': 'child eating rice with a spoon',
    '睡覺': 'child sleeping in bed',
    '洗澡': 'child in a bathtub with bubbles',
    '刷牙': 'child brushing teeth',
    '上學': 'child with backpack walking to school',
    '玩具': 'pile of toys',
    '書包': 'school backpack',
    '學校': 'school building',
    '老師': 'teacher at a blackboard',
    '朋友': 'two children holding hands',
    '太陽': 'sun',
    '月亮': 'crescent moon',
    '下雨': 'rain cloud with raindrops',
    '星星': 'star',
    '冰淇淋': 'ice cream cone',
    '巧克力': 'chocolate bar',
    '幼兒園': 'kindergarten building with playground',
    '腳踏車': 'bicycle',
    '洗衣機': 'washing machine',
    '電視機': 'television',
    '小白兔': 'white rabbit',
    '大野狼': 'grey wolf',
    '小汽車': 'small car',
    '溜滑梯': 'playground slide',
    '火車': 'steam train',
    '飛機': 'airplane',
    '輪船': 'big ship',
    '帆船': 'sailboat',
    '機車': 'scooter',
    '卡車': 'truck',
    '警車': 'police car',
    '火箭': 'rocket',
    '捷運': 'metro train',
    '救護車': 'ambulance',
    '消防車': 'fire engine',
    '直升機': 'helicopter',
    '計程車': 'yellow taxi',
    '小雞': 'baby chick',
    '小豬': 'piglet',
    '小馬': 'pony',
    '乳牛': 'dairy cow',
    '綿羊': 'fluffy sheep',
    '鴨子': 'duck',
    '老鼠': 'little mouse',
    '蜜蜂': 'honeybee',
    '螞蟻': 'ant',
    '企鵝': 'penguin',
    '烏龜': 'turtle',
    '斑馬': 'zebra',
    '章魚': 'octopus',
    '鯨魚': 'whale',
    '恐龍': 'friendly dinosaur',
    '狐狸': 'fox',
    '刺蝟': 'hedgehog',
    '長頸鹿': 'giraffe',
    '無尾熊': 'koala',
    '麵條': 'bowl of noodles',
    '披薩': 'slice of pizza',
    '漢堡': 'hamburger',
    '薯條': 'french fries',
    '飯糰': 'rice ball',
    '壽司': 'sushi',
    '餃子': 'dumplings',
    '蜂蜜': 'honey pot',
    '棒棒糖': 'lollipop',
    '爆米花': 'popcorn',
    '甜甜圈': 'donut',
    '橘子': 'orange (fruit)',
    '檸檬': 'lemon',
    '鳳梨': 'pineapple',
    '桃子': 'peach',
    '櫻桃': 'cherries',
    '玉米': 'corn cob',
    '番茄': 'tomato',
    '蘑菇': 'mushroom',
    '茄子': 'eggplant',
    '紅蘿蔔': 'carrot',
    '衣服': 't-shirt',
    '褲子': 'trousers',
    '裙子': 'dress',
    '帽子': 'sun hat',
    '鞋子': 'sneakers',
    '襪子': 'socks',
    '手套': 'mittens',
    '圍巾': 'knitted scarf',
    '雨傘': 'umbrella',
    '眼鏡': 'eyeglasses',
    '靴子': 'rain boots',
    '外套': 'coat',
    '鬧鐘': 'alarm clock',
    '電話': 'old telephone',
    '手機': 'mobile phone',
    '電腦': 'laptop computer',
    '燈泡': 'light bulb',
    '鑰匙': 'key',
    '剪刀': 'scissors',
    '鉛筆': 'pencil',
    '書本': 'open book',
    '鈴鐺': 'bell',
    '蠟燭': 'candle',
    '馬桶': 'toilet',
    '氣球': 'balloon',
    '禮物': 'gift box',
    '花朵': 'tulip flower',
    '大樹': 'big tree',
    '小草': 'little sprout',
    '葉子': 'green leaves',
    '楓葉': 'red maple leaf',
    '高山': 'mountain',
    '火山': 'volcano',
    '大海': 'sea waves',
    '沙灘': 'sandy beach',
    '貝殼': 'seashell',
    '彩虹': 'rainbow',
    '閃電': 'lightning bolt',
    '雪人': 'snowman',
    '向日葵': 'sunflower',
    '仙人掌': 'cactus',
    '跑步': 'child running',
    '游泳': 'child swimming',
    '唱歌': 'child singing with a microphone',
    '跳舞': 'child dancing',
    '畫畫': 'child painting with a palette',
    '釣魚': 'fishing rod catching a fish',
    '洗手': 'washing hands with soap',
    '拍手': 'clapping hands',
    '揮手': 'waving hand',
    '哭泣': 'crying child',
    '生氣': 'angry child',
    '足球': 'soccer ball',
    '籃球': 'basketball',
    '醫生': 'doctor',
    '警察': 'police officer',
    '廚師': 'chef',
    '農夫': 'farmer',
    '公主': 'princess',
    '國王': 'king',
    '小丑': 'clown',
    '巫師': 'friendly wizard',
    '消防員': 'firefighter',
    '太空人': 'astronaut',
    '螃蟹': 'crab',
    '海豚': 'dolphin',
    '鯊魚': 'shark',
    '瓢蟲': 'ladybug',
    '蝸牛': 'snail',
    '毛毛蟲': 'caterpillar',
    '蜘蛛': 'spider',
    '蚊子': 'mosquito',
    '蟋蟀': 'cricket',
    '老鷹': 'eagle',
    '鸚鵡': 'parrot',
    '天鵝': 'swan',
    '鴿子': 'dove',
    '袋鼠': 'kangaroo',
    '河馬': 'hippo',
    '犀牛': 'rhinoceros',
    '駱駝': 'camel',
    '松鼠': 'squirrel',
    '蝙蝠': 'bat',
    '鱷魚': 'crocodile',
    '山羊': 'goat',
    '鋼琴': 'piano',
    '吉他': 'guitar',
    '小提琴': 'violin',
    '喇叭': 'trumpet',
    '麥克風': 'microphone',
    '音樂': 'musical notes',
    '耳機': 'headphones',
    '網球': 'tennis ball',
    '排球': 'volleyball',
    '棒球': 'baseball',
    '羽球': 'badminton shuttlecock and racket',
    '滑雪': 'skiing child',
    '衝浪': 'surfing child',
    '溜冰': 'ice skate',
    '滑板': 'skateboard',
    '拳擊': 'boxing glove',
    '風箏': 'kite',
    '拼圖': 'jigsaw puzzle piece',
    '骰子': 'dice',
    '積木': 'toy building blocks',
    '帳篷': 'tent',
    '摩天輪': 'ferris wheel',
    '城堡': 'castle',
    '皇冠': 'crown',
    '寶石': 'gem',
    '生日': 'birthday cake with candles',
    '聖誕樹': 'christmas tree',
    '煙火': 'fireworks',
    '燈籠': 'red paper lantern',
    '紅包': 'red envelope',
    '南瓜': 'pumpkin',
    '雲朵': 'fluffy cloud',
    '雪花': 'snowflake',
    '颱風': 'typhoon swirl',
    '冰塊': 'ice cube',
    '火焰': 'flame',
    '水滴': 'water drop',
    '松樹': 'pine tree',
    '玫瑰': 'rose',
    '沙漠': 'desert with cactus',
    '流星': 'shooting star',
    '地球': 'planet earth',
    '牛排': 'steak',
    '熱狗': 'hot dog',
    '三明治': 'sandwich',
    '布丁': 'pudding',
    '咖啡': 'cup of coffee',
    '果汁': 'juice box',
    '火鍋': 'hot pot',
    '便當': 'bento box',
    '咖哩': 'curry rice',
    '沙拉': 'salad bowl',
    '起司': 'cheese',
    '湯匙': 'spoon',
    '筷子': 'chopsticks',
    '叉子': 'fork',
    '刀子': 'kitchen knife',
    '奶瓶': 'baby bottle',
    '芒果': 'mango',
    '椰子': 'coconut',
    '馬鈴薯': 'potato',
    '地瓜': 'sweet potato',
    '辣椒': 'red chili pepper',
    '大蒜': 'garlic',
    '洋蔥': 'onion',
    '花生': 'peanuts',
    '栗子': 'chestnut',
    '梨子': 'pear',
    '沙發': 'sofa',
    '椅子': 'chair',
    '大門': 'door',
    '掃把': 'broom',
    '相機': 'camera',
    '電池': 'battery',
    '信封': 'envelope',
    '月曆': 'calendar',
    '地圖': 'map',
    '手錶': 'wristwatch',
    '床鋪': 'bed',
    '護士': 'nurse',
    '畫家': 'painter',
    '歌手': 'singer',
    '科學家': 'scientist',
    '工人': 'construction worker',
    '偵探': 'detective',
    '天使': 'angel',
    '美人魚': 'mermaid',
    '超人': 'superhero',
    '精靈': 'elf',
    '機器人': 'robot',
    '大笑': 'laughing face',
    '害怕': 'scared face',
    '驚訝': 'surprised face',
    '思考': 'thinking face',
    '發燒': 'face with thermometer',
    '擁抱': 'hugging face',
    '愛心': 'red heart',
    '噴嚏': 'sneezing face',
    '醫院': 'hospital',
    '房子': 'house',
    '郵局': 'post office',
    '銀行': 'bank',
    '工廠': 'factory',
    '教堂': 'church',
    '紅綠燈': 'traffic light',
    '加油站': 'gas station',
    '飛碟': 'flying saucer',
    '拖拉機': 'tractor',
    '纜車': 'cable car',
    '魷魚': 'squid',
    '龍蝦': 'lobster',
    '熱帶魚': 'tropical fish',
    '河豚': 'pufferfish',
    '麋鹿': 'deer with antlers',
    '獵豹': 'cheetah',
    '哈密瓜': 'melon',
    '綠茶': 'cup of green tea',
    '月餅': 'mooncake',
    '刨冰': 'shaved ice dessert',
    '鹽巴': 'salt shaker',
    '奶油': 'butter',
    '青菜': 'leafy green vegetable',
    '汽水': 'soda cup with straw',
    '蠟筆': 'crayon',
    '毛筆': 'paintbrush',
    '原子筆': 'pen',
    '迴紋針': 'paperclip',
    '放大鏡': 'magnifying glass',
    '望遠鏡': 'telescope',
    '顯微鏡': 'microscope',
    '磁鐵': 'horseshoe magnet',
    '鐵鎚': 'hammer',
    '收音機': 'radio',
    '衛生紙': 'toilet paper roll',
    '海綿': 'sponge',
    '口罩': 'face with mask',
    '藥丸': 'pill',
    '針筒': 'syringe',
    '繃帶': 'adhesive bandage',
    '聽診器': 'stethoscope',
    '錢包': 'purse',
    '鈔票': 'banknote',
    '手提包': 'handbag',
    '高跟鞋': 'high heel shoe',
    '涼鞋': 'sandal',
    '領帶': 'shirt and necktie',
    '泳衣': 'swimsuit',
    '口紅': 'lipstick',
    '戒指': 'ring',
    '安全帽': 'rescue helmet',
    '電車': 'tram',
    '賽車': 'racing car',
    '吉普車': 'jeep',
    '獨木舟': 'canoe',
    '快艇': 'speedboat',
    '貨車': 'truck',
    '降落傘': 'parachute',
    '火車站': 'train station',
    '郵輪': 'cruise ship',
    '龍捲風': 'tornado',
    '稻穗': 'rice stalks',
    '滿月': 'full moon',
    '銀河': 'milky way',
    '噴泉': 'fountain',
    '寺廟': 'temple',
    '鐵塔': 'tall tower',
    '旅館': 'hotel',
    '商店': 'store',
    '石像': 'stone statue',
    '鬼魂': 'friendly ghost',
    '衛兵': 'guard',
    '飛行員': 'pilot',
    '法官': 'judge',
    '學生': 'student',
    '老人': 'old person',
    '新娘': 'bride',
    '新郎': 'groom',
    '走路': 'walking person',
    '舉手': 'raising hand',
    '鞠躬': 'bowing person',
    '寫字': 'writing hand',
    '握手': 'handshake',
    '祈禱': 'praying hands',
    '攀岩': 'rock climbing',
    '肌肉': 'flexed arm muscle',
    '舌頭': 'tongue',
    '大腦': 'brain',
    '骨頭': 'bone',
    '撲克牌': 'playing card',
    '保齡球': 'bowling',
    '獎牌': 'medal',
    '金牌': 'gold medal',
    '鞭炮': 'firecracker',
    '電影': 'movie clapperboard',
    '門票': 'ticket',
    '國旗': 'flags',
    '水母': 'jellyfish',
    '海豹': 'seal',
    '珊瑚': 'coral',
    '蟑螂': 'cockroach',
    '蚯蚓': 'earthworm',
    '甲蟲': 'beetle',
    '烏鴉': 'crow',
    '驢子': 'donkey',
    '狗熊': 'bear',
    '茶壺': 'teapot',
    '鏡子': 'mirror',
    '窗戶': 'window',
    '牙刷': 'toothbrush',
    '梳子': 'comb',
    '扇子': 'folding fan',
    '拖鞋': 'flip-flop slippers',
    '梯子': 'ladder',
    '鋸子': 'saw',
    '盆栽': 'potted plant',
    '石頭': 'rock',
    '木頭': 'wood log',
    '奶茶': 'bubble tea',
    '硬幣': 'coin',
    '救生圈': 'life ring',
    '泡泡': 'bubbles',
    '羽毛': 'feather',
    '翅膀': 'wing',
    '手風琴': 'accordion',
    '橄欖': 'olives',
}


def words_in_order():
    # 有圖的詞，照遊戲裡的順序（src/syllables.js 的 WORD_TEXT）；只聽不看圖的詞沒有 WORD_ICON，不用生圖
    m = open(os.path.join(ROOT, 'src', 'syllables.js'), encoding='utf-8').read()
    text = re.findall(r"^  '([^']+)': '([^']+)',$", m[m.index('WORD_TEXT = {'):m.index('WORD_ICON = {')], re.M)
    icons = set(re.findall(r"^  '([^']+)': ", m[m.index('WORD_ICON = {'):], re.M))
    return [t for z, t in text if z in icons]


def word_sheets():
    # 每九個詞一張九宮格；最後一張不滿九個就排成一列
    ws = words_in_order()
    out = []
    for i in range(0, len(ws), 9):
        chunk = ws[i:i + 9]
        rows, cols = (3, 3) if len(chunk) == 9 else (1, len(chunk))
        out.append({'name': 'words-%d' % (len(out) + 1), 'words': chunk, 'rows': rows, 'cols': cols})
    return out


def sheet_prompt(sheet):
    items = [GLOSS[w] for w in sheet['words']]
    common = ("with wide plain white gaps between them, on a plain pure white background. "
              "All the same size and the same style: " + STYLE + ". No borders, no labels. ")
    if sheet['rows'] == 1:
        return ("A single row of %d separate small illustrations side by side, " % len(items)) + common + \
            'Left to right: ' + '; '.join(items) + '.'
    rows = ' '.join('Row %d, left to right: %s.' % (r + 1, '; '.join(items[r * 3:r * 3 + 3])) for r in range(3))
    return "A 3 by 3 grid of nine separate small illustrations, each centered in its own cell, " + common + rows


def all_items():
    # 整份清單，照優先順序。每項：group、file、title、kind（處理方式）、ref（要上傳的參考圖）、prompt
    items = [{'group': 'dog0', 'file': 'dog-0', 'title': '警察柴犬（隊長，先生這張）', 'kind': 'dog', 'color': '#4A6FA5',
              'ref': None, 'prompt': DOG_BASE}]
    for f, name, color, change in DOGS:
        items.append({'group': 'dogs', 'file': f, 'title': name, 'kind': 'dog', 'color': color,
                      'ref': 'img/dog-0.png', 'prompt': DOG_EDIT.format(change=change)})
    for f, name, desc in CARDS:
        items.append({'group': 'cards', 'file': f, 'title': name, 'kind': 'card',
                      'ref': 'img/home.jpg', 'prompt': desc + ', ' + CARD_TAIL})
    for f, used, desc in BGS:
        items.append({'group': 'bgs', 'file': f, 'title': used, 'kind': 'bg',
                      'ref': 'img/home.jpg', 'prompt': desc + ', ' + BG_TAIL})
    for sh in word_sheets():
        items.append({'group': 'words', 'file': sh['name'], 'title': '、'.join(sh['words']), 'kind': 'sheet',
                      'ref': 'img/home.jpg', 'prompt': sheet_prompt(sh),
                      'words': sh['words'], 'rows': sh['rows'], 'cols': sh['cols']})
    return items
